title: #Word On the Street
author: Liam Price
email: priceliam883@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for offering new perspectives on all the intricate curveballs life may throw at you

# social links
twitter_username: therealliamprice # DO NOT include the @ character, or else the build will fail!
github_username:  priceliam3 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
